# NumPy Practice

This notebook gives you hands-on practice with the core NumPy skills from `01_Introduction_to_Numpy.ipynb`. You will create arrays in several ways, inspect their properties, reshape and index into them, and apply arithmetic operations, both element-wise and along a specific axis. Work through the challenges in order, as later ones build on earlier results.

---

## Starter Code

In [1]:
# Import NumPy, run this cell first
import numpy as np

## Part 1: Creating Arrays

### Challenge 1: Array from a list

Create a NumPy array from the following Python list:

```python
my_list = [1, 2, 5, 6, 8]
```

Print the array and its `dtype`.

In [4]:
# YOUR CODE HERE
my_list = [1, 2, 5, 6, 8]
my_arr = np.array(my_list)
print(my_arr)
print(my_arr.dtype)

[1 2 5 6 8]
int64


### Challenge 2: Range array

Create a NumPy array containing the integers from **1 to 10** (inclusive).

In [ ]:
# YOUR CODE HERE
arr = np.arange(1, 11)


[ 1  2  3  4  5  6  7  8  9 10]


dtype('int64')

### Challenge 3: Float range array

Create a NumPy array from **0 to 5** with a step size of **0.2**.

In [10]:
# YOUR CODE HERE
fl_arr = np.arange(0, 5.2, 0.2)
print(fl_arr)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]


### Challenge 4: Random array

Create a NumPy array with shape **(2, 3)** filled with random values between 0 and 1.

In [14]:
# YOUR CODE HERE
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.79641007, 0.60671583, 0.5117076 ],
       [0.61383215, 0.68024125, 0.48016899]])

---

## Part 2: Manipulating Arrays

### Challenge 5: Array with mixed-type input

Create a NumPy array from the values `(1, 3, '4', 7, 12, '0')`. Force the data type to **integer** using the `dtype` parameter.

> Notice that the string values `'4'` and `'0'` are silently cast to integers. NumPy arrays are homogeneous: all elements must share the same type.

In [33]:
# YOUR CODE HERE
data_list = [1, 3, "4", 7, 12, "0"]
mix_arr = np.array(data_list, dtype=np.int32)

print(mix_arr)
print(mix_arr.dtype)


[ 1  3  4  7 12  0]
int32


### Challenge 6: Inspect dtype and shape

Using the array you created in Challenge 5, check:
- The **data type** of the elements
- The **shape** of the array

In [27]:
# YOUR CODE HERE
data_type = print(mix_arr.dtype)
data_shape = print(mix_arr.shape)

int32
(6,)


### Challenge 7: Update a value by index

Update the **4th element** (index 3) of the array from Challenge 5 to the value `30`.

In [34]:
# YOUR CODE HERE
mix_arr[3] = 30
print(mix_arr)

[ 1  3  4 30 12  0]


### Challenge 8: Reshape to a 2×3 matrix

Reshape the array from Challenge 7 into a **2-row, 3-column** matrix. Print the result.

In [36]:
# YOUR CODE HERE
resh_arr = mix_arr.reshape(2,3)
print(resh_arr)

[[ 1  3  4]
 [30 12  0]]


### Challenge 9: Row-wise addition

Using the 2×3 matrix from Challenge 8:
- Add **8** to every value in the **first row**
- Add **12** to every value in the **second row**

> Hint: index the rows and assign back in place.

In [38]:
# YOUR CODE HERE
add_arr = resh_arr + [[8], [12]]
print(add_arr)

[[ 9 11 12]
 [42 24 12]]


### Challenge 10: Column-wise multiplication

Multiply the columns of your matrix:
- **First column** × 2
- **Second column** × 3
- **Third column** × 4

> Hint: you can do this in one line using broadcasting with a 1D array `[2, 3, 4]`.

In [39]:
# YOUR CODE HERE
mul_arr = resh_arr * [2, 3, 4]
print(mul_arr)

[[ 2  9 16]
 [60 36  0]]


### Challenge 11: Row sums

Calculate the **sum of all values in each row** of your matrix. You should get two totals, one per row.

In [45]:
# YOUR CODE HERE
row_sum = resh_arr.sum(axis = 1)
print(row_sum)


[ 8 42]


### Challenge 12: Column maximums

Find the **largest value in each column** of your matrix. You should get three values, one per column.

In [47]:
# YOUR CODE HERE
max_val_cols = resh_arr.max(axis = 0)
print(max_val_cols)

[30 12  4]


### Challenge 13: Index a single element

Extract the value from the **second column, first row** of your matrix.

> Reminder: NumPy uses `array[row, column]` indexing.

In [49]:
# YOUR CODE HERE
val = resh_arr[0, 1]
print(val)

3


### Challenge 14: Find the index of a specific value

Find the **index** of the value `48` in your matrix.

> Hint: use `np.where()`. Note that depending on how your array evolved across previous challenges, your value at a given position may differ, first check what values are currently in the matrix.

In [53]:
# YOUR CODE HERE
val48 = np.where(mul_arr == 60)
print(val48)

(array([1]), array([0]))
